export const mockParticipant = [
  {
    uuid: '-M19fOjT-Bd4MoL6EhMs',
    age: '33',
    androidVersion: '6',
    cellularAccess: '250MB',
    city: 'newTaipei',
    deviceId: '123',
    email: 'sean831004@hotmail.com',
    gender: 'male',
    mailMethod: 'appValid',
    name: 'Sean Chang',
    occupation: 'ffadadsd',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'oppo',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    status: 'appValid',
    timestamp: 'Fri Feb 28 2020 15:23:17 GMT+0800 (Taipei Standard Time)'
  }, {
    uuid: '-M19fOjT-Bd4MoL6EhMs',
    age: '33',
    androidVersion: '6',
    cellularAccess: '250MB',
    city: 'newTaipei',
    deviceId: '123',
    email: 'sean831004@hotmail.com',
    gender: 'male',
    mailMethod: 'appValid',
    name: 'Sean Chang',
    occupation: 'ffadadsd',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'oppo',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    status: 'appValid',
    timestamp: 'Fri Feb 28 2020 15:23:17 GMT+0800 (Taipei Standard Time)'
  }, {
    uuid: '-M19fOjT-Bd4MoL6EhMs',
    age: '33',
    androidVersion: '6',
    cellularAccess: '250MB',
    city: 'newTaipei',
    deviceId: '123',
    email: 'sean831004@hotmail.com',
    gender: 'male',
    mailMethod: 'appValid',
    name: 'Sean Chang',
    occupation: 'ffadadsd',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'oppo',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    status: 'appValid',
    timestamp: 'Fri Feb 28 2020 15:23:17 GMT+0800 (Taipei Standard Time)'
  },
  {
    uuid: '-M1jcOuXaSpSujBMpmvH',
    age: '22',
    androidVersion: '8',
    cellularAccess: '250MB',
    city: 'taoyuan',
    email: 'vivi160638@gmail.com',
    gender: 'female',
    mailMethod: 'selfDeliver',
    name: '安安',
    occupation: 'student',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0999999999',
    phoneSystem: 'android',
    status: 'consentValid',
    timestamp: 'Fri Mar 06 2020 11:36:11 GMT+0000 (Coordinated Universal Time)'
  },
  {
    uuid: '-M1jcOuXaSpSujBMpmvH',
    age: '22',
    androidVersion: '8',
    cellularAccess: '250MB',
    city: 'taoyuan',
    email: 'vivi160638@gmail.com',
    gender: 'female',
    mailMethod: 'selfDeliver',
    name: '安安',
    occupation: 'student',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0999999999',
    phoneSystem: 'android',
    status: 'consentValid',
    timestamp: 'Fri Mar 06 2020 11:36:11 GMT+0000 (Coordinated Universal Time)'
  },
  {
    uuid: '-M1jcOuXaSpSujBMpmvH',
    age: '22',
    androidVersion: '8',
    cellularAccess: '250MB',
    city: 'taoyuan',
    email: 'vivi160638@gmail.com',
    gender: 'female',
    mailMethod: 'selfDeliver',
    name: '安安',
    occupation: 'student',
    onlineFrequency: 'constantly',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0999999999',
    phoneSystem: 'android',
    status: 'consentValid',
    timestamp: 'Fri Mar 06 2020 11:36:11 GMT+0000 (Coordinated Universal Time)'
  }
]

export const mockCandidate = [
  {
    uuid: '-M2lcPXeEg8CXz9vFVO-',
    age: '55',
    androidVersion: '7',
    brandName: 'kkk',
    cellularAccess: '500MB',
    city: 'newTaipei',
    email: 'sean831004@gmail.com',
    gender: 'female',
    name: 'Sean Chang',
    occupation: 'service',
    onlineFrequency: 'serveralTimesAWeek',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    timestamp: 'Thu Mar 19 2020 15:11:08 GMT+0800 (Taipei Standard Time)'
  }, {
    uuid: '-M2lcPXeEg8CXz9vFVO-',
    age: '55',
    androidVersion: '7',
    brandName: 'kkk',
    cellularAccess: '500MB',
    city: 'newTaipei',
    email: 'sean831004@gmail.com',
    gender: 'female',
    name: 'Sean Chang',
    occupation: 'service',
    onlineFrequency: 'serveralTimesAWeek',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    timestamp: 'Thu Mar 19 2020 15:11:08 GMT+0800 (Taipei Standard Time)'
  }, {
    uuid: '-M2lcPXeEg8CXz9vFVO-',
    age: '55',
    androidVersion: '7',
    brandName: 'kkk',
    cellularAccess: '500MB',
    city: 'newTaipei',
    email: 'sean831004@gmail.com',
    gender: 'female',
    name: 'Sean Chang',
    occupation: 'service',
    onlineFrequency: 'serveralTimesAWeek',
    personOfInterest: false,
    phoneBrand: 'samsung',
    phoneNumber: '0975068858',
    phoneSystem: 'android',
    timestamp: 'Thu Mar 19 2020 15:11:08 GMT+0800 (Taipei Standard Time)'
  }
]
